import flash.display.Bitmap;

class Fs_stand_17_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_12_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_17_png extends Bitmap { public function new() { super(); } }
class Fly_right_1_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_30_png extends Bitmap { public function new() { super(); } }
class Pp_win_9_png extends Bitmap { public function new() { super(); } }
class Ts_backup_4_png extends Bitmap { public function new() { super(); } }
class T_fall_11_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_34_png extends Bitmap { public function new() { super(); } }
class Pp_fall_1_png extends Bitmap { public function new() { super(); } }
class Ts_win_16_png extends Bitmap { public function new() { super(); } }
class Fs_super_15_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__12_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_3_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_5_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_1_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_17_png extends Bitmap { public function new() { super(); } }
class Fs_hop_6_png extends Bitmap { public function new() { super(); } }
class Pp_stand_6_png extends Bitmap { public function new() { super(); } }
class Ts_win_44_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_22_png extends Bitmap { public function new() { super(); } }
class Ts_stand_3_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_14_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_13_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_10_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_16_png extends Bitmap { public function new() { super(); } }
class Ts_win_25_png extends Bitmap { public function new() { super(); } }
class Pp_win_10_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_1_png extends Bitmap { public function new() { super(); } }
class Ts_win_45_png extends Bitmap { public function new() { super(); } }
class Teleport_right_16_png extends Bitmap { public function new() { super(); } }
class Bg_tank__8_png extends Bitmap { public function new() { super(); } }
class Bg_tank__18_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_12_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_0_png extends Bitmap { public function new() { super(); } }
class Fs_super_22_png extends Bitmap { public function new() { super(); } }
class Ts_win_5_png extends Bitmap { public function new() { super(); } }
class Ra_stand_skip_1_png extends Bitmap { public function new() { super(); } }
class Ts_backup_1_png extends Bitmap { public function new() { super(); } }
class Ts_stand_14_png extends Bitmap { public function new() { super(); } }
class Fs_super_9_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__14_png extends Bitmap { public function new() { super(); } }
class Pp_jump_3_png extends Bitmap { public function new() { super(); } }
class Fs_fly_9_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_5_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__8_png extends Bitmap { public function new() { super(); } }
class R_jump_1_png extends Bitmap { public function new() { super(); } }
class Fs_super_19_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_14_png extends Bitmap { public function new() { super(); } }
class Teleport_right_24_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_3_png extends Bitmap { public function new() { super(); } }
class R_jump_14_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_25_png extends Bitmap { public function new() { super(); } }
class Fs_super_25_png extends Bitmap { public function new() { super(); } }
class Ts_win_1_png extends Bitmap { public function new() { super(); } }
class Pp_stand_15_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_35_png extends Bitmap { public function new() { super(); } }
class Ts_win_18_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_14_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_2_png extends Bitmap { public function new() { super(); } }
class R_stand_7_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_1_png extends Bitmap { public function new() { super(); } }
class Pp_stand_10_png extends Bitmap { public function new() { super(); } }
class Fs_fall_3_png extends Bitmap { public function new() { super(); } }
class Bgcrop_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_16_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_27_png extends Bitmap { public function new() { super(); } }
class Montage_png extends Bitmap { public function new() { super(); } }
class Bg_tank__2_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_10_png extends Bitmap { public function new() { super(); } }
class Fs_super_1_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__9_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_22_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_0_png extends Bitmap { public function new() { super(); } }
class Fs_super_0_png extends Bitmap { public function new() { super(); } }
class Pp_falloff_5_png extends Bitmap { public function new() { super(); } }
class Ts_win_31_png extends Bitmap { public function new() { super(); } }
class Teleport_right_7_png extends Bitmap { public function new() { super(); } }
class Ts_win_26_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_11_png extends Bitmap { public function new() { super(); } }
class Fs_sleep_1_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_0_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_19_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_5_png extends Bitmap { public function new() { super(); } }
class Fs_fall_2_png extends Bitmap { public function new() { super(); } }
class Fs_stand_13_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_4_png extends Bitmap { public function new() { super(); } }
class Fs_stand_15_png extends Bitmap { public function new() { super(); } }
class Pp_fall_4_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_0_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_26_png extends Bitmap { public function new() { super(); } }
class R_stand_10_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_9_png extends Bitmap { public function new() { super(); } }
class Teleport_right_27_png extends Bitmap { public function new() { super(); } }
class R_stand_2_png extends Bitmap { public function new() { super(); } }
class Teleport_right_13_png extends Bitmap { public function new() { super(); } }
class Fs_super_7_png extends Bitmap { public function new() { super(); } }
class Bg_tank__14_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_5_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_8_png extends Bitmap { public function new() { super(); } }
class Bg_tank__1_png extends Bitmap { public function new() { super(); } }
class Fs_fall_7_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_13_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_7_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_10_png extends Bitmap { public function new() { super(); } }
class Fs_stand_2_png extends Bitmap { public function new() { super(); } }
class Pp_jump_8_png extends Bitmap { public function new() { super(); } }
class Fs_hop_10_png extends Bitmap { public function new() { super(); } }
class Ts_backup_13_png extends Bitmap { public function new() { super(); } }
class Ts_stand_5_png extends Bitmap { public function new() { super(); } }
class Ts_win_47_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_12_png extends Bitmap { public function new() { super(); } }
class Sb_pointnear_1_png extends Bitmap { public function new() { super(); } }
class T_fall_3_png extends Bitmap { public function new() { super(); } }
class R_stand_13_png extends Bitmap { public function new() { super(); } }
class Pp_copter_8_png extends Bitmap { public function new() { super(); } }
class Pp_stand_13_png extends Bitmap { public function new() { super(); } }
class Bg_tank__10_png extends Bitmap { public function new() { super(); } }
class Pp_copter_19_png extends Bitmap { public function new() { super(); } }
class R_stand_6_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_5_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_8_png extends Bitmap { public function new() { super(); } }
class Pp_fall_2_png extends Bitmap { public function new() { super(); } }
class Fs_stand_9_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__10_png extends Bitmap { public function new() { super(); } }
class Fs_fall_11_png extends Bitmap { public function new() { super(); } }
class Teleport_right_2_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_15_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_32_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_38_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_4_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_3_png extends Bitmap { public function new() { super(); } }
class Fs_super_12_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_19_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_37_png extends Bitmap { public function new() { super(); } }
class Sb_pointnear_3_png extends Bitmap { public function new() { super(); } }
class T_fall_9_png extends Bitmap { public function new() { super(); } }
class R_jump_15_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_7_png extends Bitmap { public function new() { super(); } }
class Pp_stand_2_png extends Bitmap { public function new() { super(); } }
class Fly_right_3_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_16_png extends Bitmap { public function new() { super(); } }
class R_jump_11_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_14_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_37_png extends Bitmap { public function new() { super(); } }
class Ts_backup_6_png extends Bitmap { public function new() { super(); } }
class Animated_12_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_0_png extends Bitmap { public function new() { super(); } }
class Pp_copter_9_png extends Bitmap { public function new() { super(); } }
class R_magic_5_png extends Bitmap { public function new() { super(); } }
class T_fall_7_png extends Bitmap { public function new() { super(); } }
class Ts_win_30_png extends Bitmap { public function new() { super(); } }
class Fs_super_31_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_0_png extends Bitmap { public function new() { super(); } }
class Pp_fly_6_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_2_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_8_png extends Bitmap { public function new() { super(); } }
class R_jump_7_png extends Bitmap { public function new() { super(); } }
class Animated_16_png extends Bitmap { public function new() { super(); } }
class Pp_jump_5_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_33_png extends Bitmap { public function new() { super(); } }
class Fs_stand_12_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_1_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_15_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_23_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_25_png extends Bitmap { public function new() { super(); } }
class Animated_9_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_12_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_0_png extends Bitmap { public function new() { super(); } }
class Pp_stand_14_png extends Bitmap { public function new() { super(); } }
class Fs_fall_10_png extends Bitmap { public function new() { super(); } }
class Ra_stand_skip_0_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_48_png extends Bitmap { public function new() { super(); } }
class Teleport_right_8_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_33_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_5_png extends Bitmap { public function new() { super(); } }
class Pp_fall_5_png extends Bitmap { public function new() { super(); } }
class T_fall_1_png extends Bitmap { public function new() { super(); } }
class Ts_backup_7_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_1_png extends Bitmap { public function new() { super(); } }
class Animated_18_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_9_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_15_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_3_png extends Bitmap { public function new() { super(); } }
class Pp_fall_16_png extends Bitmap { public function new() { super(); } }
class Fs_stand_16_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__4_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_11_png extends Bitmap { public function new() { super(); } }
class Bg_tank__3_png extends Bitmap { public function new() { super(); } }
class Pp_fall_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_32_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_4_png extends Bitmap { public function new() { super(); } }
class Ts_win_4_png extends Bitmap { public function new() { super(); } }
class Fs_super_30_png extends Bitmap { public function new() { super(); } }
class Fs_fall_13_png extends Bitmap { public function new() { super(); } }
class Animated_22_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_1_png extends Bitmap { public function new() { super(); } }
class Cloud_png extends Bitmap { public function new() { super(); } }
class R_stand_1_png extends Bitmap { public function new() { super(); } }
class Ts_win_29_png extends Bitmap { public function new() { super(); } }
class Ts_win_34_png extends Bitmap { public function new() { super(); } }
class Pp_jump_1_png extends Bitmap { public function new() { super(); } }
class Pp_win_4_png extends Bitmap { public function new() { super(); } }
class Pp_copter_2_png extends Bitmap { public function new() { super(); } }
class Bg_png extends Bitmap { public function new() { super(); } }
class Ts_win_40_png extends Bitmap { public function new() { super(); } }
class Ts_win_20_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_4_png extends Bitmap { public function new() { super(); } }
class R_stand_15_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_5_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_21_png extends Bitmap { public function new() { super(); } }
class Pp_fall_17_png extends Bitmap { public function new() { super(); } }
class Ice_png extends Bitmap { public function new() { super(); } }
class Fs_hop_13_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_17_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_3_png extends Bitmap { public function new() { super(); } }
class T_fall_13_png extends Bitmap { public function new() { super(); } }
class Fs_super_8_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_4_png extends Bitmap { public function new() { super(); } }
class Teleport_right_15_png extends Bitmap { public function new() { super(); } }
class R_jump_0_png extends Bitmap { public function new() { super(); } }
class Ts_stand_11_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__15_png extends Bitmap { public function new() { super(); } }
class T_fall_0_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__3_png extends Bitmap { public function new() { super(); } }
class Teleport_right_32_png extends Bitmap { public function new() { super(); } }
class Ts_win_12_png extends Bitmap { public function new() { super(); } }
class Fs_super_10_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_45_png extends Bitmap { public function new() { super(); } }
class T_fall_10_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_3_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_3_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_13_png extends Bitmap { public function new() { super(); } }
class Teleport_right_1_png extends Bitmap { public function new() { super(); } }
class Ts_win_6_png extends Bitmap { public function new() { super(); } }
class Ts_win_42_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_4_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_7_png extends Bitmap { public function new() { super(); } }
class Animated_11_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_2_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_4_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_23_png extends Bitmap { public function new() { super(); } }
class Fs_super_33_png extends Bitmap { public function new() { super(); } }
class Fs_stand_5_png extends Bitmap { public function new() { super(); } }
class Teleport_right_17_png extends Bitmap { public function new() { super(); } }
class Fs_fall_5_png extends Bitmap { public function new() { super(); } }
class Pp_win_2_png extends Bitmap { public function new() { super(); } }
class Pp_stand_5_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_11_png extends Bitmap { public function new() { super(); } }
class Bg_tank__15_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_11_png extends Bitmap { public function new() { super(); } }
class Teleport_right_30_png extends Bitmap { public function new() { super(); } }
class Ts_win_59_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_15_png extends Bitmap { public function new() { super(); } }
class Teleport_right_19_png extends Bitmap { public function new() { super(); } }
class Fs_super_32_png extends Bitmap { public function new() { super(); } }
class Ts_win_15_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_2_png extends Bitmap { public function new() { super(); } }
class Cloud2_png extends Bitmap { public function new() { super(); } }
class Fs_fly_0_png extends Bitmap { public function new() { super(); } }
class Pp_copter_14_png extends Bitmap { public function new() { super(); } }
class Pp_copter_17_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__5_png extends Bitmap { public function new() { super(); } }
class Fs_fall_12_png extends Bitmap { public function new() { super(); } }
class Teleport_right_14_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_9_png extends Bitmap { public function new() { super(); } }
class Animated_6_png extends Bitmap { public function new() { super(); } }
class Teleport_right_5_png extends Bitmap { public function new() { super(); } }
class Sb_pointnear_4_png extends Bitmap { public function new() { super(); } }
class Fs_super_11_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_9_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__1_png extends Bitmap { public function new() { super(); } }
class R_stand_11_png extends Bitmap { public function new() { super(); } }
class Pp_jump_6_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_2_png extends Bitmap { public function new() { super(); } }
class Ra_stand_jump_0_png extends Bitmap { public function new() { super(); } }
class Ts_stand_15_png extends Bitmap { public function new() { super(); } }
class Sb_pointnear_2_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_11_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_2_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_7_png extends Bitmap { public function new() { super(); } }
class Ts_win_19_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_1_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_9_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_13_png extends Bitmap { public function new() { super(); } }
class Animated_7_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_10_png extends Bitmap { public function new() { super(); } }
class Pp_jump_10_png extends Bitmap { public function new() { super(); } }
class R_jump_5_png extends Bitmap { public function new() { super(); } }
class Pp_copter_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_43_png extends Bitmap { public function new() { super(); } }
class Fs_super_28_png extends Bitmap { public function new() { super(); } }
class Animated_4_png extends Bitmap { public function new() { super(); } }
class R_magic_0_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_31_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_40_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_9_png extends Bitmap { public function new() { super(); } }
class Ts_win_53_png extends Bitmap { public function new() { super(); } }
class Ts_stand_2_png extends Bitmap { public function new() { super(); } }
class R_jump_4_png extends Bitmap { public function new() { super(); } }
class Pp_fly_3_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_14_png extends Bitmap { public function new() { super(); } }
class Pp_stand_12_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_7_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_8_png extends Bitmap { public function new() { super(); } }
class Fs_super_24_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_21_png extends Bitmap { public function new() { super(); } }
class Fs_hop_11_png extends Bitmap { public function new() { super(); } }
class Fs_super_6_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_5_png extends Bitmap { public function new() { super(); } }
class Ts_stand_7_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_6_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_1_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_12_png extends Bitmap { public function new() { super(); } }
class Fs_fly_1_png extends Bitmap { public function new() { super(); } }
class Ts_backup_3_png extends Bitmap { public function new() { super(); } }
class Ra_stand_jump_1_png extends Bitmap { public function new() { super(); } }
class Pp_copter_10_png extends Bitmap { public function new() { super(); } }
class Ra_magic_left_0_png extends Bitmap { public function new() { super(); } }
class Fs_super_27_png extends Bitmap { public function new() { super(); } }
class Fs_fall_4_png extends Bitmap { public function new() { super(); } }
class Fs_fly_5_png extends Bitmap { public function new() { super(); } }
class Sb_point_3_png extends Bitmap { public function new() { super(); } }
class Pp_falloff_4_png extends Bitmap { public function new() { super(); } }
class Animated_20_png extends Bitmap { public function new() { super(); } }
class Fs_stand_3_png extends Bitmap { public function new() { super(); } }
class Ts_win_17_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_3_png extends Bitmap { public function new() { super(); } }
class Fly_right_2_png extends Bitmap { public function new() { super(); } }
class Sb_point_5_png extends Bitmap { public function new() { super(); } }
class Fs_fall_0_png extends Bitmap { public function new() { super(); } }
class Pp_falloff_2_png extends Bitmap { public function new() { super(); } }
class Fs_hop_15_png extends Bitmap { public function new() { super(); } }
class Ts_backup_12_png extends Bitmap { public function new() { super(); } }
class Animated_2_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_11_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__6_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_6_png extends Bitmap { public function new() { super(); } }
class Ts_stand_9_png extends Bitmap { public function new() { super(); } }
class Pp_copter_4_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_7_png extends Bitmap { public function new() { super(); } }
class R_magic_2_png extends Bitmap { public function new() { super(); } }
class Animated_1_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_4_png extends Bitmap { public function new() { super(); } }
class Montage_stand_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_14_png extends Bitmap { public function new() { super(); } }
class Fs_stand_0_png extends Bitmap { public function new() { super(); } }
class R_jump_12_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_7_png extends Bitmap { public function new() { super(); } }
class Fs_fly_15_png extends Bitmap { public function new() { super(); } }
class Ts_win_35_png extends Bitmap { public function new() { super(); } }
class Pp_fall_11_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__13_png extends Bitmap { public function new() { super(); } }
class Fly_right_0_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_5_png extends Bitmap { public function new() { super(); } }
class Animated_19_png extends Bitmap { public function new() { super(); } }
class R_magic_4_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_16_png extends Bitmap { public function new() { super(); } }
class Fs_super_16_png extends Bitmap { public function new() { super(); } }
class R_stand_0_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_35_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_15_png extends Bitmap { public function new() { super(); } }
class Pp_jump_11_png extends Bitmap { public function new() { super(); } }
class Ts_win_51_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_4_png extends Bitmap { public function new() { super(); } }
class Fs_super_23_png extends Bitmap { public function new() { super(); } }
class Fs_hop_1_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_7_png extends Bitmap { public function new() { super(); } }
class Pp_stand_1_png extends Bitmap { public function new() { super(); } }
class Sb_pointnear_5_png extends Bitmap { public function new() { super(); } }
class Bg_tank__5_png extends Bitmap { public function new() { super(); } }
class Teleport_right_4_png extends Bitmap { public function new() { super(); } }
class Pp_fall_12_png extends Bitmap { public function new() { super(); } }
class Animated_13_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_10_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_1_png extends Bitmap { public function new() { super(); } }
class Ts_win_10_png extends Bitmap { public function new() { super(); } }
class Ts_win_3_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_11_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_15_png extends Bitmap { public function new() { super(); } }
class Ra_stand_skip_4_png extends Bitmap { public function new() { super(); } }
class Ts_win_22_png extends Bitmap { public function new() { super(); } }
class Pp_stand_4_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_3_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_47_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_7_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_17_png extends Bitmap { public function new() { super(); } }
class Ts_win_8_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_27_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_7_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__7_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_2_png extends Bitmap { public function new() { super(); } }
class Fs_fly_11_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_2_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_24_png extends Bitmap { public function new() { super(); } }
class Fs_super_13_png extends Bitmap { public function new() { super(); } }
class Ts_win_0_png extends Bitmap { public function new() { super(); } }
class Ts_backup_10_png extends Bitmap { public function new() { super(); } }
class Sb_point_1_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_3_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_42_png extends Bitmap { public function new() { super(); } }
class R_stand_5_png extends Bitmap { public function new() { super(); } }
class Fs_super_5_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_41_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_15_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_36_png extends Bitmap { public function new() { super(); } }
class Animated_25_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_9_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_10_png extends Bitmap { public function new() { super(); } }
class Sb_point_0_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_5_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_7_png extends Bitmap { public function new() { super(); } }
class Animated_15_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_31_png extends Bitmap { public function new() { super(); } }
class Pp_fall_15_png extends Bitmap { public function new() { super(); } }
class Animated_23_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_13_png extends Bitmap { public function new() { super(); } }
class Teleport_right_3_png extends Bitmap { public function new() { super(); } }
class Fs_super_20_png extends Bitmap { public function new() { super(); } }
class Pp_fall_8_png extends Bitmap { public function new() { super(); } }
class Ts_win_57_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_14_png extends Bitmap { public function new() { super(); } }
class Fs_stand_4_png extends Bitmap { public function new() { super(); } }
class Fs_stand_14_png extends Bitmap { public function new() { super(); } }
class Ra_stand_jump_4_png extends Bitmap { public function new() { super(); } }
class Ts_win_56_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_5_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_2_png extends Bitmap { public function new() { super(); } }
class Sb_point_2_png extends Bitmap { public function new() { super(); } }
class Fs_fall_1_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_16_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_2_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_4_png extends Bitmap { public function new() { super(); } }
class Ts_stand_6_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_5_png extends Bitmap { public function new() { super(); } }
class Teleport_right_0_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_17_png extends Bitmap { public function new() { super(); } }
class Ts_win_50_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_2_png extends Bitmap { public function new() { super(); } }
class Fs_super_3_png extends Bitmap { public function new() { super(); } }
class Ts_win_55_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_3_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_4_png extends Bitmap { public function new() { super(); } }
class Ts_backup_9_png extends Bitmap { public function new() { super(); } }
class Pp_fly_0_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_20_png extends Bitmap { public function new() { super(); } }
class T_fall_5_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_10_png extends Bitmap { public function new() { super(); } }
class Fs_super_26_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_10_png extends Bitmap { public function new() { super(); } }
class Fs_stand_7_png extends Bitmap { public function new() { super(); } }
class Teleport_right_25_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_54_png extends Bitmap { public function new() { super(); } }
class T_fall_8_png extends Bitmap { public function new() { super(); } }
class Ts_win_46_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_2_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__2_png extends Bitmap { public function new() { super(); } }
class Fs_fly_7_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_15_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_9_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_13_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_16_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_10_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_5_png extends Bitmap { public function new() { super(); } }
class Pp_jump_7_png extends Bitmap { public function new() { super(); } }
class Ts_win_38_png extends Bitmap { public function new() { super(); } }
class R_jump_3_png extends Bitmap { public function new() { super(); } }
class Pp_win_11_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_8_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_46_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_4_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_1_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_19_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_0_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_8_png extends Bitmap { public function new() { super(); } }
class Ts_stand_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_52_png extends Bitmap { public function new() { super(); } }
class R_jump_9_png extends Bitmap { public function new() { super(); } }
class Teleport_right_31_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_33_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_18_png extends Bitmap { public function new() { super(); } }
class Sb_sit_2_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_9_png extends Bitmap { public function new() { super(); } }
class Pp_copter_1_png extends Bitmap { public function new() { super(); } }
class Pp_fall_10_png extends Bitmap { public function new() { super(); } }
class Bg_tank__7_png extends Bitmap { public function new() { super(); } }
class Pp_stand_7_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_13_png extends Bitmap { public function new() { super(); } }
class Ts_stand_13_png extends Bitmap { public function new() { super(); } }
class Ts_backup_5_png extends Bitmap { public function new() { super(); } }
class T_fall_2_png extends Bitmap { public function new() { super(); } }
class R_jump_6_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_44_png extends Bitmap { public function new() { super(); } }
class R_stand_12_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_3_png extends Bitmap { public function new() { super(); } }
class Ts_stand_12_png extends Bitmap { public function new() { super(); } }
class Ts_win_58_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_32_png extends Bitmap { public function new() { super(); } }
class Ts_backup_8_png extends Bitmap { public function new() { super(); } }
class Fs_hop_0_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_2_png extends Bitmap { public function new() { super(); } }
class Teleport_right_34_png extends Bitmap { public function new() { super(); } }
class Fs_fall_8_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_0_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_11_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_43_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_1_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_10_png extends Bitmap { public function new() { super(); } }
class Fs_hop_4_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_1_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_13_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_11_png extends Bitmap { public function new() { super(); } }
class Pp_copter_15_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_14_png extends Bitmap { public function new() { super(); } }
class Ra_magic_left_2_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_4_png extends Bitmap { public function new() { super(); } }
class Ra_magic_left_1_png extends Bitmap { public function new() { super(); } }
class Ra_magic_left_3_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_26_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_6_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_23_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_13_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_31_png extends Bitmap { public function new() { super(); } }
class Bg_tank__6_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_8_png extends Bitmap { public function new() { super(); } }
class Pp_stand_9_png extends Bitmap { public function new() { super(); } }
class Pp_copter_18_png extends Bitmap { public function new() { super(); } }
class Ts_win_28_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_34_png extends Bitmap { public function new() { super(); } }
class Pp_fly_5_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_6_png extends Bitmap { public function new() { super(); } }
class T_fall_6_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_2_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_17_png extends Bitmap { public function new() { super(); } }
class Ts_win_23_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_7_png extends Bitmap { public function new() { super(); } }
class Pp_fly_2_png extends Bitmap { public function new() { super(); } }
class Pp_fly_1_png extends Bitmap { public function new() { super(); } }
class Pp_win_6_png extends Bitmap { public function new() { super(); } }
class Fs_fall_6_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_0_png extends Bitmap { public function new() { super(); } }
class Animated_24_png extends Bitmap { public function new() { super(); } }
class Fs_sleep_0_png extends Bitmap { public function new() { super(); } }
class Pp_stand_8_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_0_png extends Bitmap { public function new() { super(); } }
class Fs_super_29_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_4_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_3_png extends Bitmap { public function new() { super(); } }
class Ts_backup_14_png extends Bitmap { public function new() { super(); } }
class Animated_8_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_15_png extends Bitmap { public function new() { super(); } }
class Pp_copter_5_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_5_png extends Bitmap { public function new() { super(); } }
class Bg_tank__13_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_18_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__0_png extends Bitmap { public function new() { super(); } }
class Fs_hop_9_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_14_png extends Bitmap { public function new() { super(); } }
class Ra_magic_left_4_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_12_png extends Bitmap { public function new() { super(); } }
class Ts_win_39_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_8_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_11_png extends Bitmap { public function new() { super(); } }
class Ts_win_49_png extends Bitmap { public function new() { super(); } }
class Pp_falloff_3_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_8_png extends Bitmap { public function new() { super(); } }
class Fs_fly_2_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_6_png extends Bitmap { public function new() { super(); } }
class T_fall_12_png extends Bitmap { public function new() { super(); } }
class Sb_point_4_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_0_png extends Bitmap { public function new() { super(); } }
class Pp_jump_4_png extends Bitmap { public function new() { super(); } }
class Bg_tank__16_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_8_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_9_png extends Bitmap { public function new() { super(); } }
class Ts_backup_2_png extends Bitmap { public function new() { super(); } }
class Pp_jump_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_21_png extends Bitmap { public function new() { super(); } }
class Pp_jump_2_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_0_png extends Bitmap { public function new() { super(); } }
class Bg_tank__19_png extends Bitmap { public function new() { super(); } }
class Pp_copter_11_png extends Bitmap { public function new() { super(); } }
class Fs_hop_2_png extends Bitmap { public function new() { super(); } }
class R_jump_13_png extends Bitmap { public function new() { super(); } }
class Teleport_right_10_png extends Bitmap { public function new() { super(); } }
class Pp_fall_6_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_6_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_1_png extends Bitmap { public function new() { super(); } }
class R_jump_2_png extends Bitmap { public function new() { super(); } }
class Ts_win_48_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_18_png extends Bitmap { public function new() { super(); } }
class Fs_stand_6_png extends Bitmap { public function new() { super(); } }
class Animated_10_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_24_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_32_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_29_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_1_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_8_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_28_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_8_png extends Bitmap { public function new() { super(); } }
class Pp_win_7_png extends Bitmap { public function new() { super(); } }
class Cloud_by_grendopony_d427jg5_png extends Bitmap { public function new() { super(); } }
class Bg_tank__17_png extends Bitmap { public function new() { super(); } }
class Pp_fall_7_png extends Bitmap { public function new() { super(); } }
class R_jump_10_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_18_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_15_png extends Bitmap { public function new() { super(); } }
class Animated_3_png extends Bitmap { public function new() { super(); } }
class Ts_win_37_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_12_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_11_png extends Bitmap { public function new() { super(); } }
class Ts_backup_11_png extends Bitmap { public function new() { super(); } }
class Ts_backup_15_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_12_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_6_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_10_png extends Bitmap { public function new() { super(); } }
class Ts_stand_4_png extends Bitmap { public function new() { super(); } }
class Pp_win_1_png extends Bitmap { public function new() { super(); } }
class Fly_right_4_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_36_png extends Bitmap { public function new() { super(); } }
class Pp_win_5_png extends Bitmap { public function new() { super(); } }
class Fs_super_17_png extends Bitmap { public function new() { super(); } }
class Pp_win_8_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_1_png extends Bitmap { public function new() { super(); } }
class Fs_super_18_png extends Bitmap { public function new() { super(); } }
class Teleport_right_33_png extends Bitmap { public function new() { super(); } }
class Pp_fall_14_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_13_png extends Bitmap { public function new() { super(); } }
class Fs_fly_4_png extends Bitmap { public function new() { super(); } }
class Fs_hop_7_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_4_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_6_png extends Bitmap { public function new() { super(); } }
class Ra_stand_skip_2_png extends Bitmap { public function new() { super(); } }
class Pp_win_3_png extends Bitmap { public function new() { super(); } }
class Ts_win_27_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_6_png extends Bitmap { public function new() { super(); } }
class Pp_copter_3_png extends Bitmap { public function new() { super(); } }
class R_stand_14_png extends Bitmap { public function new() { super(); } }
class Sb_sit_3_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_1_png extends Bitmap { public function new() { super(); } }
class Sb_pointnear_0_png extends Bitmap { public function new() { super(); } }
class Fs_fly_6_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_20_png extends Bitmap { public function new() { super(); } }
class Ts_win_24_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_34_png extends Bitmap { public function new() { super(); } }
class Fly_right_6_png extends Bitmap { public function new() { super(); } }
class Teleport_right_12_png extends Bitmap { public function new() { super(); } }
class Fs_super_21_png extends Bitmap { public function new() { super(); } }
class Animated_21_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_right_4_png extends Bitmap { public function new() { super(); } }
class Pp_copter_13_png extends Bitmap { public function new() { super(); } }
class Ts_win_36_png extends Bitmap { public function new() { super(); } }
class Pp_fall_13_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_11_png extends Bitmap { public function new() { super(); } }
class Fs_fly_8_png extends Bitmap { public function new() { super(); } }
class T_fall_4_png extends Bitmap { public function new() { super(); } }
class Ts_win_2_png extends Bitmap { public function new() { super(); } }
class Ts_stand_10_png extends Bitmap { public function new() { super(); } }
class Pp_fall_3_png extends Bitmap { public function new() { super(); } }
class Fs_super_2_png extends Bitmap { public function new() { super(); } }
class Ponyless_cloud_by_grendopony_d470xwq_png extends Bitmap { public function new() { super(); } }
class Pp_copter_6_png extends Bitmap { public function new() { super(); } }
class Bounce_pinkiepie_up_down_right_6_png extends Bitmap { public function new() { super(); } }
class Pp_fly_4_png extends Bitmap { public function new() { super(); } }
class Fs_super_14_png extends Bitmap { public function new() { super(); } }
class Sb_jump_left_1_png extends Bitmap { public function new() { super(); } }
class Fs_stand_1_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_49_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_6_png extends Bitmap { public function new() { super(); } }
class Pp_copter_16_png extends Bitmap { public function new() { super(); } }
class R_magic_1_png extends Bitmap { public function new() { super(); } }
class Ra_magic_left_5_png extends Bitmap { public function new() { super(); } }
class Ts_stand_8_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_11_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_27_png extends Bitmap { public function new() { super(); } }
class Sb_jump_right_2_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_29_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_30_png extends Bitmap { public function new() { super(); } }
class Sb_sit_0_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_28_png extends Bitmap { public function new() { super(); } }
class Sb_sit_1_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_12_png extends Bitmap { public function new() { super(); } }
class Ra_magic_redo_6_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_7_png extends Bitmap { public function new() { super(); } }
class Ts_backup_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_41_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_14_png extends Bitmap { public function new() { super(); } }
class Bg_tank__9_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_9_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_10_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_8_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_26_png extends Bitmap { public function new() { super(); } }
class Fs_fly_3_png extends Bitmap { public function new() { super(); } }
class Pp_jump_9_png extends Bitmap { public function new() { super(); } }
class Fs_hop_3_png extends Bitmap { public function new() { super(); } }
class R_magic_3_png extends Bitmap { public function new() { super(); } }
class Fs_stand_11_png extends Bitmap { public function new() { super(); } }
class Ts_win_11_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_7_png extends Bitmap { public function new() { super(); } }
class Bg_tank__4_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_7_png extends Bitmap { public function new() { super(); } }
class Teleport_right_22_png extends Bitmap { public function new() { super(); } }
class Bg_tank__11_png extends Bitmap { public function new() { super(); } }
class Stand_Pinkiepie_right_12_png extends Bitmap { public function new() { super(); } }
class Teleport_right_11_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_9_png extends Bitmap { public function new() { super(); } }
class R_stand_4_png extends Bitmap { public function new() { super(); } }
class Fs_stand_8_png extends Bitmap { public function new() { super(); } }
class R_stand_3_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_2_png extends Bitmap { public function new() { super(); } }
class Teleport_right_29_png extends Bitmap { public function new() { super(); } }
class Derpy_fly_4_png extends Bitmap { public function new() { super(); } }
class Fs_fly_14_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_21_png extends Bitmap { public function new() { super(); } }
class Fs_fall_9_png extends Bitmap { public function new() { super(); } }
class Teleport_right_9_png extends Bitmap { public function new() { super(); } }
class Teleport_right_23_png extends Bitmap { public function new() { super(); } }
class Pp_falloff_0_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_5_png extends Bitmap { public function new() { super(); } }
class Bg_spitfire__11_png extends Bitmap { public function new() { super(); } }
class Fs_fly_13_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_13_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_8_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_6_png extends Bitmap { public function new() { super(); } }
class Pp_fall_9_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_39_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_3_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_10_png extends Bitmap { public function new() { super(); } }
class Teleport_right_21_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_15_png extends Bitmap { public function new() { super(); } }
class Ts_win_13_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_6_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_5_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_11_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_3_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_20_png extends Bitmap { public function new() { super(); } }
class Pp_copter_12_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_28_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_0_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_2_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_24_png extends Bitmap { public function new() { super(); } }
class Ts_win_7_png extends Bitmap { public function new() { super(); } }
class Animated_0_png extends Bitmap { public function new() { super(); } }
class Ts_win_33_png extends Bitmap { public function new() { super(); } }
class Derpy_upsidedown_6_png extends Bitmap { public function new() { super(); } }
class Ts_win_9_png extends Bitmap { public function new() { super(); } }
class Rd_bg_zoom_14_png extends Bitmap { public function new() { super(); } }
class Teleport_right_28_png extends Bitmap { public function new() { super(); } }
class Fs_hop_12_png extends Bitmap { public function new() { super(); } }
class Fs_hop_5_png extends Bitmap { public function new() { super(); } }
class Pp_stand_3_png extends Bitmap { public function new() { super(); } }
class R_jump_8_png extends Bitmap { public function new() { super(); } }
class Ts_stand_1_png extends Bitmap { public function new() { super(); } }
class Pp_stand_0_png extends Bitmap { public function new() { super(); } }
class Pp_falloff_1_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_0_png extends Bitmap { public function new() { super(); } }
class Teleport_right_6_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_9_png extends Bitmap { public function new() { super(); } }
class Animated_27_png extends Bitmap { public function new() { super(); } }
class Animated_5_png extends Bitmap { public function new() { super(); } }
class Fs_fly_10_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_30_png extends Bitmap { public function new() { super(); } }
class Teleport_right_18_png extends Bitmap { public function new() { super(); } }
class Pp_cupcake_29_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_22_png extends Bitmap { public function new() { super(); } }
class Fs_hop_8_png extends Bitmap { public function new() { super(); } }
class Ra_stand_jump_3_png extends Bitmap { public function new() { super(); } }
class Bg_tank__12_png extends Bitmap { public function new() { super(); } }
class R_stand_9_png extends Bitmap { public function new() { super(); } }
class Pinkie_disappear_right_14_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_3_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_5_png extends Bitmap { public function new() { super(); } }
class Fly_right_5_png extends Bitmap { public function new() { super(); } }
class Fs_stand_10_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_6_png extends Bitmap { public function new() { super(); } }
class Pp_stand_11_png extends Bitmap { public function new() { super(); } }
class Fs_super_4_png extends Bitmap { public function new() { super(); } }
class Pp_copter_stop_25_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_7_png extends Bitmap { public function new() { super(); } }
class Bg_tank__0_png extends Bitmap { public function new() { super(); } }
class Ts_arrive_18_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_3_png extends Bitmap { public function new() { super(); } }
class Fs_fly_12_png extends Bitmap { public function new() { super(); } }
class Animated_14_png extends Bitmap { public function new() { super(); } }
class Pp_win_0_png extends Bitmap { public function new() { super(); } }
class Animated_17_png extends Bitmap { public function new() { super(); } }
class Stand_twilight_right_12_png extends Bitmap { public function new() { super(); } }
class Fs_hop_14_png extends Bitmap { public function new() { super(); } }
class Teleport_right_26_png extends Bitmap { public function new() { super(); } }
class Arrive_Right_10_png extends Bitmap { public function new() { super(); } }
class Ra_stand_jump_2_png extends Bitmap { public function new() { super(); } }
class Ra_stand_skip_3_png extends Bitmap { public function new() { super(); } }
class Animated_26_png extends Bitmap { public function new() { super(); } }
class Teleport_right_20_png extends Bitmap { public function new() { super(); } }
class Sb_sit_4_png extends Bitmap { public function new() { super(); } }
class Pp_jumpnn_6_png extends Bitmap { public function new() { super(); } }
class Ts_teleport_9_png extends Bitmap { public function new() { super(); } }
class Pp_copter_7_png extends Bitmap { public function new() { super(); } }
class R_stand_8_png extends Bitmap { public function new() { super(); } }
